std = 'max'
globals = {
  'apply_theme',
  'contains',
  'file_exists',
  'find_executable',
  'get_all_local_config',
  'get_local_config',
  'get_or',
  'global_keymap',
  'handle_vim_event',
  'parent_dir',
  'project_root',
  'set',
  'set_config',
  'slugify',
  'source',
  'split',
  'touch',
  'trim_right',
  'use_theme',
  'vim',
}
