std = 'max'
globals = {
  'apply_theme',
  'file_exists',
  'find_executable',
  'get_all_local_config',
  'get_or',
  'get_user_config',
  'global_keymap',
  'handle_vim_event_by_callback',
  'handle_vim_event_by_command',
  'parent_dir',
  'project_root',
  'readfile',
  'set',
  'set_user_config',
  'slugify',
  'source',
  'touch',
  'trim_right',
  'use_theme',
  'writefile',
  'vim',
}
